### ISSUE TITLE
Briefings: Tableau Integration

### ISSUE THREAD

**Issue by WillieShubert** [oeco/opendev-wptheme#20] opened 2015-02-07 07:15 UTC
Clicking on the embedded tableau graphics on the energy sector briefing pushes you back up the the top of the page.  

Reference: http://cambodia.opendevelopmentmekong.net/briefings/the-cambodian-energy-sector/#

**Comment by miguelpeixe** [comment] 2015-02-07 16:46
Hey @WillieShubert 

This tableau doesn't look properly embedded. It's just an image with a link to nowhere (that's why it goes to the top of the page when you click it)

**Comment by DBishton** [comment] 2015-02-10 09:48
Thanks Willie,

This was caused by a WP permissions issue that was removing code from posts made by users without Super-admin permissions. This permissions issue has now been resolved, and I've followed up with Pinkie to re-post the broken Tableau embed code blocks in the ODC Briefings.

**Comment by miguelpeixe** [comment] 2015-02-13 19:51
Can we close this issue?

**Comment by WillieShubert** [comment] 2015-02-13 20:00
Yes. It looks to be working fine.

**Closed as completed** 2015-02-27 18:42 UTC
